// 抖音表情映射表（自动生成）
// 从 hnlyzxf/douyin-emoji 仓库提取

export interface DouyinEmojiItem {
  code: string;
  name: string;
  url: string;
}

export const DOUYIN_EMOJI_MAP: Record<string, string> = {
  "[微笑]": "/emoji/douyin/weixiao.png",
  "[色]": "/emoji/douyin/aimu.png",
  "[发呆]": "/emoji/douyin/liangdai.png",
  "[酷拽]": "/emoji/douyin/kuye.png",
  "[抠鼻]": "/emoji/douyin/koubi.png",
  "[流泪]": "/emoji/douyin/liulei.png",
  "[捂脸]": "/emoji/douyin/wulian.png",
  "[发怒]": "/emoji/douyin/fanu.png",
  "[呲牙]": "/emoji/douyin/ziya.png",
  "[尬笑]": "/emoji/douyin/gaxiao.png",
  "[害羞]": "/emoji/douyin/haixiu.png",
  "[调皮]": "/emoji/douyin/keai.png",
  "[舔屏]": "/emoji/douyin/tianping.png",
  "[看]": "/emoji/douyin/kan.png",
  "[爱心]": "/emoji/douyin/xin.png",
  "[比心]": "/emoji/douyin/bixin.png",
  "[赞]": "/emoji/douyin/zan.png",
  "[鼓掌]": "/emoji/douyin/guzhang.png",
  "[感谢]": "/emoji/douyin/qidao.png",
  "[抱抱你]": "/emoji/douyin/baobaoni.png",
  "[玫瑰]": "/emoji/douyin/meigui.png",
  "[尴尬流汗]": "/emoji/douyin/gangaliuhan.png",
  "[戳手手]": "/emoji/douyin/chuoshoushou.png",
  "[星星眼]": "/emoji/douyin/xingxingyan.png",
  "[杀马特]": "/emoji/douyin/shamate.png",
  "[黄脸干杯]": "/emoji/douyin/huanglianganbei.png",
  "[抱紧自己]": "/emoji/douyin/baojinziji.png",
  "[拜拜]": "/emoji/douyin/baibai.png",
  "[热化了]": "/emoji/douyin/rehuale.png",
  "[黄脸祈祷]": "/emoji/douyin/huanglianqidao.png",
  "[懵]": "/emoji/douyin/meng.png",
  "[举手]": "/emoji/douyin/jushou.png",
  "[加功德]": "/emoji/douyin/jiagongde.png",
  "[摊手]": "/emoji/douyin/tanshou.png",
  "[无语流汗]": "/emoji/douyin/wuyuliuhan.png",
  "[续火花吧]": "/emoji/douyin/xuhuohuaba.png",
  "[点火]": "/emoji/douyin/dianhuo.png",
  "[哭哭]": "/emoji/douyin/kuku.png",
  "[吐舌小狗]": "/emoji/douyin/tushexiaogou.png",
  "[送花]": "/emoji/douyin/songhua.png",
  "[爱心手]": "/emoji/douyin/aixinshou.png",
  "[贴贴]": "/emoji/douyin/tietie.png",
  "[灵机一动]": "/emoji/douyin/lingguangyishan.png",
  "[耶]": "/emoji/douyin/ye.png",
  "[打脸]": "/emoji/douyin/dalian.png",
  "[大笑]": "/emoji/douyin/daxiao.png",
  "[机智]": "/emoji/douyin/jizhi.png",
  "[送心]": "/emoji/douyin/songxin.png",
  "[666]": "/emoji/douyin/666.png",
  "[闭嘴]": "/emoji/douyin/bizui.png",
  "[来看我]": "/emoji/douyin/laikanwo.png",
  "[一起加油]": "/emoji/douyin/yiqijiayou.png",
  "[哈欠]": "/emoji/douyin/haqian.png",
  "[震惊]": "/emoji/douyin/zhenliang.png",
  "[晕]": "/emoji/douyin/yun.png",
  "[衰]": "/emoji/douyin/shuai.png",
  "[困]": "/emoji/douyin/kun.png",
  "[疑问]": "/emoji/douyin/what.png",
  "[泣不成声]": "/emoji/douyin/qibuchengsheng.png",
  "[小鼓掌]": "/emoji/douyin/xiaoguzhang.png",
  "[大金牙]": "/emoji/douyin/dajinya.png",
  "[偷笑]": "/emoji/douyin/touxiao.png",
  "[石化]": "/emoji/douyin/shihua.png",
  "[思考]": "/emoji/douyin/sikao.png",
  "[吐血]": "/emoji/douyin/tuxie.png",
  "[可怜]": "/emoji/douyin/kelian.png",
  "[嘘]": "/emoji/douyin/xu.png",
  "[撇嘴]": "/emoji/douyin/piezui.png",
  "[笑哭]": "/emoji/douyin/xiaoku.png",
  "[奸笑]": "/emoji/douyin/jianxiao.png",
  "[得意]": "/emoji/douyin/deyi.png",
  "[憨笑]": "/emoji/douyin/hanxiao.png",
  "[坏笑]": "/emoji/douyin/huaixiao.png",
  "[抓狂]": "/emoji/douyin/zhuakuang.png",
  "[泪奔]": "/emoji/douyin/leiben.png",
  "[钱]": "/emoji/douyin/qian.png",
  "[恐惧]": "/emoji/douyin/kongju.png",
  "[愉快]": "/emoji/douyin/xiao.png",
  "[快哭了]": "/emoji/douyin/kuaikule.png",
  "[翻白眼]": "/emoji/douyin/fanbaiyan.png",
  "[互粉]": "/emoji/douyin/hufen.png",
  "[我想静静]": "/emoji/douyin/woxiangjingjing.png",
  "[委屈]": "/emoji/douyin/weiqu.png",
  "[鄙视]": "/emoji/douyin/bishi.png",
  "[飞吻]": "/emoji/douyin/feiwen.png",
  "[再见]": "/emoji/douyin/zaijian.png",
  "[紫薇别走]": "/emoji/douyin/ziweibiezou.png",
  "[听歌]": "/emoji/douyin/tingge.png",
  "[求抱抱]": "/emoji/douyin/qiubaobao.png",
  "[绝望的凝视]": "/emoji/douyin/zhoudongyudeningshi.png",
  "[不失礼貌的微笑]": "/emoji/douyin/masichundeweixiao.png",
  "[不看]": "/emoji/douyin/bukan.png",
  "[裂开]": "/emoji/douyin/liekai.png",
  "[干饭人]": "/emoji/douyin/ganfanren.png",
  "[庆祝]": "/emoji/douyin/qingzhu.png",
  "[吐舌]": "/emoji/douyin/tushe.png",
  "[呆无辜]": "/emoji/douyin/daiwugu.png",
  "[白眼]": "/emoji/douyin/baiyan.png",
  "[猪头]": "/emoji/douyin/zhutou.png",
  "[冷漠]": "/emoji/douyin/lengmo.png",
  "[暗中观察]": "/emoji/douyin/anzhongguancha.png",
  "[二哈]": "/emoji/douyin/erha.png",
  "[菜狗]": "/emoji/douyin/caigou.png",
  "[黑脸]": "/emoji/douyin/heilian.png",
  "[展开说说]": "/emoji/douyin/zhankaishuoshuo.png",
  "[蜜蜂狗]": "/emoji/douyin/mifenggou.png",
  "[柴犬]": "/emoji/douyin/huangchaiquan.png",
  "[摸头]": "/emoji/douyin/motou.png",
  "[皱眉]": "/emoji/douyin/zhoumei.png",
  "[擦汗]": "/emoji/douyin/cahan.png",
  "[红脸]": "/emoji/douyin/honglian.png",
  "[做鬼脸]": "/emoji/douyin/zuoguilian.png",
  "[强]": "/emoji/douyin/qiang.png",
  "[如花]": "/emoji/douyin/ruhua.png",
  "[吐]": "/emoji/douyin/tu.png",
  "[惊喜]": "/emoji/douyin/liangxi.png",
  "[敲打]": "/emoji/douyin/qiaoda.png",
  "[奋斗]": "/emoji/douyin/fendou.png",
  "[吐彩虹]": "/emoji/douyin/tucaihong.png",
  "[大哭]": "/emoji/douyin/daku.png",
  "[嘿哈]": "/emoji/douyin/heiha.png",
  "[惊恐]": "/emoji/douyin/jingkong.png",
  "[囧]": "/emoji/douyin/jiong.png",
  "[难过]": "/emoji/douyin/nanguo.png",
  "[斜眼]": "/emoji/douyin/xieyan.png",
  "[阴险]": "/emoji/douyin/yinxian.png",
  "[悠闲]": "/emoji/douyin/youxian.png",
  "[咒骂]": "/emoji/douyin/zhouma.png",
  "[吃瓜群众]": "/emoji/douyin/chiguaqunzhong.png",
  "[绿帽子]": "/emoji/douyin/lvmaozi.png",
  "[敢怒不敢言]": "/emoji/douyin/gannubuganyan.png",
  "[求求了]": "/emoji/douyin/qiuqiule.png",
  "[眼含热泪]": "/emoji/douyin/yanhanrelei.png",
  "[叹气]": "/emoji/douyin/tanqi.png",
  "[好开心]": "/emoji/douyin/haokaixin.png",
  "[不是吧]": "/emoji/douyin/bushiba.png",
  "[鞠躬]": "/emoji/douyin/jugong.png",
  "[躺平]": "/emoji/douyin/tangping.png",
  "[九转大肠]": "/emoji/douyin/jiuzhuandachang.png",
  "[不你不想]": "/emoji/douyin/bunibuxiang.png",
  "[一头乱麻]": "/emoji/douyin/yitouluanma.png",
  "[kisskiss]": "/emoji/douyin/kisskiss.png",
  "[你不大行]": "/emoji/douyin/nibudaxing.png",
  "[噢买尬]": "/emoji/douyin/omg.png",
  "[宕机]": "/emoji/douyin/dangji.png",
  "[苦涩]": "/emoji/douyin/kuse.png",
  "[逞强落泪]": "/emoji/douyin/chengqiangluolei.png",
  "[求机位-黄脸]": "/emoji/douyin/huanglianqiujiwei.png",
  "[求机位3]": "/emoji/douyin/qiujiwei3.png",
  "[点赞]": "/emoji/douyin/jingxuan.png",
  "[精选]": "/emoji/douyin/jingxuanzan.png",
  "[强壮]": "/emoji/douyin/jiayou.png",
  "[碰拳]": "/emoji/douyin/pengquan.png",
  "[OK]": "/emoji/douyin/ok.png",
  "[击掌]": "/emoji/douyin/jizhang.png",
  "[左上]": "/emoji/douyin/zuoshang.png",
  "[握手]": "/emoji/douyin/woshou.png",
  "[抱拳]": "/emoji/douyin/baoquan.png",
  "[勾引]": "/emoji/douyin/gouyin.png",
  "[拳头]": "/emoji/douyin/quantou.png",
  "[弱]": "/emoji/douyin/ruo.png",
  "[胜利]": "/emoji/douyin/shengli.png",
  "[右边]": "/emoji/douyin/youbian.png",
  "[左边]": "/emoji/douyin/zuobian.png",
  "[嘴唇]": "/emoji/douyin/kiss.png",
  "[心碎]": "/emoji/douyin/shangxin.png",
  "[凋谢]": "/emoji/douyin/diaoxie.png",
  "[愤怒]": "/emoji/douyin/fennu.png",
  "[垃圾]": "/emoji/douyin/laji.png",
  "[啤酒]": "/emoji/douyin/pijiu.png",
  "[咖啡]": "/emoji/douyin/kafei.png",
  "[蛋糕]": "/emoji/douyin/dangao.png",
  "[礼物]": "/emoji/douyin/liwu.png",
  "[撒花]": "/emoji/douyin/sahua.png",
  "[加一]": "/emoji/douyin/jiayi.png",
  "[减一]": "/emoji/douyin/jianyi.png",
  "[okk]": "/emoji/douyin/okk.png",
  "[V5]": "/emoji/douyin/V5.png",
  "[绝]": "/emoji/douyin/jue.png",
  "[给力]": "/emoji/douyin/geili.png",
  "[红包]": "/emoji/douyin/hongbao.png",
  "[屎]": "/emoji/douyin/shi.png",
  "[发]": "/emoji/douyin/fa.png",
  "[18禁]": "/emoji/douyin/18jin.png",
  "[炸弹]": "/emoji/douyin/zhadan.png",
  "[西瓜]": "/emoji/douyin/xigua.png",
  "[加鸡腿]": "/emoji/douyin/jiajitui.png",
  "[握爪]": "/emoji/douyin/wozhua.png",
  "[太阳]": "/emoji/douyin/taiyang.png",
  "[月亮]": "/emoji/douyin/yueliang.png",
  "[给跪了]": "/emoji/douyin/geiguile.png",
  "[蕉绿]": "/emoji/douyin/jiaolv.png",
  "[扎心]": "/emoji/douyin/zhaxin.png",
  "[胡瓜]": "/emoji/douyin/hugua.png",
  "[打call]": "/emoji/douyin/dacall.png",
  "[栓Q]": "/emoji/douyin/shuanq.png",
  "[雪花]": "/emoji/douyin/xuehua.png",
  "[圣诞树]": "/emoji/douyin/shengdanshu.png",
  "[平安果]": "/emoji/douyin/pinganguo.png",
  "[圣诞帽]": "/emoji/douyin/shengdanmao.png",
  "[气球]": "/emoji/douyin/qiqiu.png",
  "[烟花]": "/emoji/douyin/yanhua.png",
  "[福]": "/emoji/douyin/fu.png",
  "[candy]": "/emoji/douyin/candy.png",
  "[糖葫芦]": "/emoji/douyin/tanghulu.png",
  "[鞭炮]": "/emoji/douyin/bianpao.png",
  "[元宝]": "/emoji/douyin/yuanbao.png",
  "[灯笼]": "/emoji/douyin/denglong.png",
  "[锦鲤]": "/emoji/douyin/jinli.png",
  "[巧克力]": "/emoji/douyin/qiaokeli.png",
  "[戒指]": "/emoji/douyin/jiezhi.png",
  "[棒棒糖]": "/emoji/douyin/bangbangtang.png",
  "[纸飞机]": "/emoji/douyin/zhifeiji.png",
  "[粽子]": "/emoji/douyin/zongzi.png",
};

export const DOUYIN_EMOJI_LIST: DouyinEmojiItem[] = [
  { code: "[微笑]", name: "微笑", url: "/emoji/douyin/weixiao.png" },
  { code: "[色]", name: "色", url: "/emoji/douyin/aimu.png" },
  { code: "[发呆]", name: "呆住", url: "/emoji/douyin/liangdai.png" },
  { code: "[酷拽]", name: "生气", url: "/emoji/douyin/kuye.png" },
  { code: "[抠鼻]", name: "抠鼻", url: "/emoji/douyin/koubi.png" },
  { code: "[流泪]", name: "流泪", url: "/emoji/douyin/liulei.png" },
  { code: "[捂脸]", name: "捂脸", url: "/emoji/douyin/wulian.png" },
  { code: "[发怒]", name: "发怒", url: "/emoji/douyin/fanu.png" },
  { code: "[呲牙]", name: "呲牙", url: "/emoji/douyin/ziya.png" },
  { code: "[尬笑]", name: "尬笑", url: "/emoji/douyin/gaxiao.png" },
  { code: "[害羞]", name: "害羞", url: "/emoji/douyin/haixiu.png" },
  { code: "[调皮]", name: "调皮", url: "/emoji/douyin/keai.png" },
  { code: "[舔屏]", name: "舔屏", url: "/emoji/douyin/tianping.png" },
  { code: "[看]", name: "狗头", url: "/emoji/douyin/kan.png" },
  { code: "[爱心]", name: "爱心", url: "/emoji/douyin/xin.png" },
  { code: "[比心]", name: "比心", url: "/emoji/douyin/bixin.png" },
  { code: "[赞]", name: "赞", url: "/emoji/douyin/zan.png" },
  { code: "[鼓掌]", name: "鼓掌", url: "/emoji/douyin/guzhang.png" },
  { code: "[感谢]", name: "双手合十", url: "/emoji/douyin/qidao.png" },
  { code: "[抱抱你]", name: "抱抱你", url: "/emoji/douyin/baobaoni.png" },
  { code: "[玫瑰]", name: "玫瑰", url: "/emoji/douyin/meigui.png" },
  { code: "[尴尬流汗]", name: "尴尬", url: "/emoji/douyin/gangaliuhan.png" },
  { code: "[戳手手]", name: "戳手手", url: "/emoji/douyin/chuoshoushou.png" },
  { code: "[星星眼]", name: "星星眼", url: "/emoji/douyin/xingxingyan.png" },
  { code: "[杀马特]", name: "杀马特", url: "/emoji/douyin/shamate.png" },
  { code: "[黄脸干杯]", name: "干杯", url: "/emoji/douyin/huanglianganbei.png" },
  { code: "[抱紧自己]", name: "抱紧自己", url: "/emoji/douyin/baojinziji.png" },
  { code: "[拜拜]", name: "拜拜", url: "/emoji/douyin/baibai.png" },
  { code: "[热化了]", name: "热化了", url: "/emoji/douyin/rehuale.png" },
  { code: "[黄脸祈祷]", name: "祈祷", url: "/emoji/douyin/huanglianqidao.png" },
  { code: "[懵]", name: "懵", url: "/emoji/douyin/meng.png" },
  { code: "[举手]", name: "举手", url: "/emoji/douyin/jushou.png" },
  { code: "[加功德]", name: "加功德", url: "/emoji/douyin/jiagongde.png" },
  { code: "[摊手]", name: "摊手", url: "/emoji/douyin/tanshou.png" },
  { code: "[无语流汗]", name: "无语", url: "/emoji/douyin/wuyuliuhan.png" },
  { code: "[续火花吧]", name: "续火花", url: "/emoji/douyin/xuhuohuaba.png" },
  { code: "[点火]", name: "点火", url: "/emoji/douyin/dianhuo.png" },
  { code: "[哭哭]", name: "哭哭", url: "/emoji/douyin/kuku.png" },
  { code: "[吐舌小狗]", name: "吐舌小狗", url: "/emoji/douyin/tushexiaogou.png" },
  { code: "[送花]", name: "送花", url: "/emoji/douyin/songhua.png" },
  { code: "[爱心手]", name: "爱心手", url: "/emoji/douyin/aixinshou.png" },
  { code: "[贴贴]", name: "贴贴", url: "/emoji/douyin/tietie.png" },
  { code: "[灵机一动]", name: "灵机一动", url: "/emoji/douyin/lingguangyishan.png" },
  { code: "[耶]", name: "耶", url: "/emoji/douyin/ye.png" },
  { code: "[打脸]", name: "打脸", url: "/emoji/douyin/dalian.png" },
  { code: "[大笑]", name: "大笑", url: "/emoji/douyin/daxiao.png" },
  { code: "[机智]", name: "还得是你", url: "/emoji/douyin/jizhi.png" },
  { code: "[送心]", name: "送心", url: "/emoji/douyin/songxin.png" },
  { code: "[666]", name: "666", url: "/emoji/douyin/666.png" },
  { code: "[闭嘴]", name: "闭嘴", url: "/emoji/douyin/bizui.png" },
  { code: "[来看我]", name: "关注我", url: "/emoji/douyin/laikanwo.png" },
  { code: "[一起加油]", name: "加油", url: "/emoji/douyin/yiqijiayou.png" },
  { code: "[哈欠]", name: "哈欠", url: "/emoji/douyin/haqian.png" },
  { code: "[震惊]", name: "震惊", url: "/emoji/douyin/zhenliang.png" },
  { code: "[晕]", name: "晕", url: "/emoji/douyin/yun.png" },
  { code: "[衰]", name: "衰", url: "/emoji/douyin/shuai.png" },
  { code: "[困]", name: "困", url: "/emoji/douyin/kun.png" },
  { code: "[疑问]", name: "疑惑", url: "/emoji/douyin/what.png" },
  { code: "[泣不成声]", name: "泣不成声", url: "/emoji/douyin/qibuchengsheng.png" },
  { code: "[小鼓掌]", name: "真棒", url: "/emoji/douyin/xiaoguzhang.png" },
  { code: "[大金牙]", name: "大金牙", url: "/emoji/douyin/dajinya.png" },
  { code: "[偷笑]", name: "偷笑", url: "/emoji/douyin/touxiao.png" },
  { code: "[石化]", name: "石化", url: "/emoji/douyin/shihua.png" },
  { code: "[思考]", name: "思考", url: "/emoji/douyin/sikao.png" },
  { code: "[吐血]", name: "吐血", url: "/emoji/douyin/tuxie.png" },
  { code: "[可怜]", name: "可怜", url: "/emoji/douyin/kelian.png" },
  { code: "[嘘]", name: "嘘", url: "/emoji/douyin/xu.png" },
  { code: "[撇嘴]", name: "撇嘴", url: "/emoji/douyin/piezui.png" },
  { code: "[笑哭]", name: "笑哭", url: "/emoji/douyin/xiaoku.png" },
  { code: "[奸笑]", name: "奸笑", url: "/emoji/douyin/jianxiao.png" },
  { code: "[得意]", name: "得意", url: "/emoji/douyin/deyi.png" },
  { code: "[憨笑]", name: "憨笑", url: "/emoji/douyin/hanxiao.png" },
  { code: "[坏笑]", name: "坏笑", url: "/emoji/douyin/huaixiao.png" },
  { code: "[抓狂]", name: "抓狂", url: "/emoji/douyin/zhuakuang.png" },
  { code: "[泪奔]", name: "泪奔", url: "/emoji/douyin/leiben.png" },
  { code: "[钱]", name: "爱钱", url: "/emoji/douyin/qian.png" },
  { code: "[恐惧]", name: "恐惧", url: "/emoji/douyin/kongju.png" },
  { code: "[愉快]", name: "愉快", url: "/emoji/douyin/xiao.png" },
  { code: "[快哭了]", name: "快哭了", url: "/emoji/douyin/kuaikule.png" },
  { code: "[翻白眼]", name: "翻白眼", url: "/emoji/douyin/fanbaiyan.png" },
  { code: "[互粉]", name: "互粉", url: "/emoji/douyin/hufen.png" },
  { code: "[我想静静]", name: "我想静静", url: "/emoji/douyin/woxiangjingjing.png" },
  { code: "[委屈]", name: "委屈", url: "/emoji/douyin/weiqu.png" },
  { code: "[鄙视]", name: "鄙视", url: "/emoji/douyin/bishi.png" },
  { code: "[飞吻]", name: "爱心飞吻", url: "/emoji/douyin/feiwen.png" },
  { code: "[再见]", name: "再见", url: "/emoji/douyin/zaijian.png" },
  { code: "[紫薇别走]", name: "别走", url: "/emoji/douyin/ziweibiezou.png" },
  { code: "[听歌]", name: "听歌", url: "/emoji/douyin/tingge.png" },
  { code: "[求抱抱]", name: "求抱抱", url: "/emoji/douyin/qiubaobao.png" },
  { code: "[绝望的凝视]", name: "无语凝视", url: "/emoji/douyin/zhoudongyudeningshi.png" },
  { code: "[不失礼貌的微笑]", name: "礼貌微笑", url: "/emoji/douyin/masichundeweixiao.png" },
  { code: "[不看]", name: "没眼看", url: "/emoji/douyin/bukan.png" },
  { code: "[裂开]", name: "裂开", url: "/emoji/douyin/liekai.png" },
  { code: "[干饭人]", name: "干饭", url: "/emoji/douyin/ganfanren.png" },
  { code: "[庆祝]", name: "庆祝", url: "/emoji/douyin/qingzhu.png" },
  { code: "[吐舌]", name: "吐舌", url: "/emoji/douyin/tushe.png" },
  { code: "[呆无辜]", name: "呆", url: "/emoji/douyin/daiwugu.png" },
  { code: "[白眼]", name: "白眼", url: "/emoji/douyin/baiyan.png" },
  { code: "[猪头]", name: "猪头", url: "/emoji/douyin/zhutou.png" },
  { code: "[冷漠]", name: "冷漠", url: "/emoji/douyin/lengmo.png" },
  { code: "[暗中观察]", name: "暗中观察", url: "/emoji/douyin/anzhongguancha.png" },
  { code: "[二哈]", name: "二哈", url: "/emoji/douyin/erha.png" },
  { code: "[菜狗]", name: "菜狗", url: "/emoji/douyin/caigou.png" },
  { code: "[黑脸]", name: "黑脸", url: "/emoji/douyin/heilian.png" },
  { code: "[展开说说]", name: "展开说说", url: "/emoji/douyin/zhankaishuoshuo.png" },
  { code: "[蜜蜂狗]", name: "蜜蜂小狗", url: "/emoji/douyin/mifenggou.png" },
  { code: "[柴犬]", name: "柴犬", url: "/emoji/douyin/huangchaiquan.png" },
  { code: "[摸头]", name: "摸头", url: "/emoji/douyin/motou.png" },
  { code: "[皱眉]", name: "皱眉", url: "/emoji/douyin/zhoumei.png" },
  { code: "[擦汗]", name: "擦汗", url: "/emoji/douyin/cahan.png" },
  { code: "[红脸]", name: "脸红", url: "/emoji/douyin/honglian.png" },
  { code: "[做鬼脸]", name: "做鬼脸", url: "/emoji/douyin/zuoguilian.png" },
  { code: "[强]", name: "强", url: "/emoji/douyin/qiang.png" },
  { code: "[如花]", name: "如花", url: "/emoji/douyin/ruhua.png" },
  { code: "[吐]", name: "吐", url: "/emoji/douyin/tu.png" },
  { code: "[惊喜]", name: "惊喜", url: "/emoji/douyin/liangxi.png" },
  { code: "[敲打]", name: "敲打", url: "/emoji/douyin/qiaoda.png" },
  { code: "[奋斗]", name: "奋斗", url: "/emoji/douyin/fendou.png" },
  { code: "[吐彩虹]", name: "吐彩虹", url: "/emoji/douyin/tucaihong.png" },
  { code: "[大哭]", name: "大哭", url: "/emoji/douyin/daku.png" },
  { code: "[嘿哈]", name: "嘿哈", url: "/emoji/douyin/heiha.png" },
  { code: "[惊恐]", name: "惊恐", url: "/emoji/douyin/jingkong.png" },
  { code: "[囧]", name: "囧", url: "/emoji/douyin/jiong.png" },
  { code: "[难过]", name: "难过", url: "/emoji/douyin/nanguo.png" },
  { code: "[斜眼]", name: "斜眼", url: "/emoji/douyin/xieyan.png" },
  { code: "[阴险]", name: "阴险", url: "/emoji/douyin/yinxian.png" },
  { code: "[悠闲]", name: "悠闲", url: "/emoji/douyin/youxian.png" },
  { code: "[咒骂]", name: "咒骂", url: "/emoji/douyin/zhouma.png" },
  { code: "[吃瓜群众]", name: "吃瓜群众", url: "/emoji/douyin/chiguaqunzhong.png" },
  { code: "[绿帽子]", name: "绿帽子", url: "/emoji/douyin/lvmaozi.png" },
  { code: "[敢怒不敢言]", name: "怒不敢言", url: "/emoji/douyin/gannubuganyan.png" },
  { code: "[求求了]", name: "求求了", url: "/emoji/douyin/qiuqiule.png" },
  { code: "[眼含热泪]", name: "眼含热泪", url: "/emoji/douyin/yanhanrelei.png" },
  { code: "[叹气]", name: "叹气", url: "/emoji/douyin/tanqi.png" },
  { code: "[好开心]", name: "好开心", url: "/emoji/douyin/haokaixin.png" },
  { code: "[不是吧]", name: "不是吧", url: "/emoji/douyin/bushiba.png" },
  { code: "[鞠躬]", name: "鞠躬", url: "/emoji/douyin/jugong.png" },
  { code: "[躺平]", name: "躺平", url: "/emoji/douyin/tangping.png" },
  { code: "[九转大肠]", name: "九转大肠", url: "/emoji/douyin/jiuzhuandachang.png" },
  { code: "[不你不想]", name: "别说了", url: "/emoji/douyin/bunibuxiang.png" },
  { code: "[一头乱麻]", name: "一头乱麻", url: "/emoji/douyin/yitouluanma.png" },
  { code: "[kisskiss]", name: "飞吻", url: "/emoji/douyin/kisskiss.png" },
  { code: "[你不大行]", name: "你不大行", url: "/emoji/douyin/nibudaxing.png" },
  { code: "[噢买尬]", name: "OMG", url: "/emoji/douyin/omg.png" },
  { code: "[宕机]", name: "宕机", url: "/emoji/douyin/dangji.png" },
  { code: "[苦涩]", name: "苦涩", url: "/emoji/douyin/kuse.png" },
  { code: "[逞强落泪]", name: "逞强落泪", url: "/emoji/douyin/chengqiangluolei.png" },
  { code: "[求机位-黄脸]", name: "求机位", url: "/emoji/douyin/huanglianqiujiwei.png" },
  { code: "[求机位3]", name: "求机位", url: "/emoji/douyin/qiujiwei3.png" },
  { code: "[点赞]", name: "点赞", url: "/emoji/douyin/jingxuan.png" },
  { code: "[精选]", name: "精选", url: "/emoji/douyin/jingxuanzan.png" },
  { code: "[强壮]", name: "强壮", url: "/emoji/douyin/jiayou.png" },
  { code: "[碰拳]", name: "碰拳", url: "/emoji/douyin/pengquan.png" },
  { code: "[OK]", name: "好的", url: "/emoji/douyin/ok.png" },
  { code: "[击掌]", name: "击掌", url: "/emoji/douyin/jizhang.png" },
  { code: "[左上]", name: "指", url: "/emoji/douyin/zuoshang.png" },
  { code: "[握手]", name: "握手", url: "/emoji/douyin/woshou.png" },
  { code: "[抱拳]", name: "抱拳", url: "/emoji/douyin/baoquan.png" },
  { code: "[勾引]", name: "勾引", url: "/emoji/douyin/gouyin.png" },
  { code: "[拳头]", name: "拳头", url: "/emoji/douyin/quantou.png" },
  { code: "[弱]", name: "弱", url: "/emoji/douyin/ruo.png" },
  { code: "[胜利]", name: "比耶", url: "/emoji/douyin/shengli.png" },
  { code: "[右边]", name: "右边", url: "/emoji/douyin/youbian.png" },
  { code: "[左边]", name: "左边", url: "/emoji/douyin/zuobian.png" },
  { code: "[嘴唇]", name: "亲", url: "/emoji/douyin/kiss.png" },
  { code: "[心碎]", name: "心碎", url: "/emoji/douyin/shangxin.png" },
  { code: "[凋谢]", name: "凋谢", url: "/emoji/douyin/diaoxie.png" },
  { code: "[愤怒]", name: "愤怒", url: "/emoji/douyin/fennu.png" },
  { code: "[垃圾]", name: "垃圾", url: "/emoji/douyin/laji.png" },
  { code: "[啤酒]", name: "啤酒", url: "/emoji/douyin/pijiu.png" },
  { code: "[咖啡]", name: "咖啡", url: "/emoji/douyin/kafei.png" },
  { code: "[蛋糕]", name: "蛋糕", url: "/emoji/douyin/dangao.png" },
  { code: "[礼物]", name: "礼物", url: "/emoji/douyin/liwu.png" },
  { code: "[撒花]", name: "撒花", url: "/emoji/douyin/sahua.png" },
  { code: "[加一]", name: "加一", url: "/emoji/douyin/jiayi.png" },
  { code: "[减一]", name: "减一", url: "/emoji/douyin/jianyi.png" },
  { code: "[okk]", name: "OK", url: "/emoji/douyin/okk.png" },
  { code: "[V5]", name: "V5", url: "/emoji/douyin/V5.png" },
  { code: "[绝]", name: "绝", url: "/emoji/douyin/jue.png" },
  { code: "[给力]", name: "给力", url: "/emoji/douyin/geili.png" },
  { code: "[红包]", name: "红包", url: "/emoji/douyin/hongbao.png" },
  { code: "[屎]", name: "便便", url: "/emoji/douyin/shi.png" },
  { code: "[发]", name: "发", url: "/emoji/douyin/fa.png" },
  { code: "[18禁]", name: "18禁", url: "/emoji/douyin/18jin.png" },
  { code: "[炸弹]", name: "炸弹", url: "/emoji/douyin/zhadan.png" },
  { code: "[西瓜]", name: "西瓜", url: "/emoji/douyin/xigua.png" },
  { code: "[加鸡腿]", name: "加鸡腿", url: "/emoji/douyin/jiajitui.png" },
  { code: "[握爪]", name: "握爪", url: "/emoji/douyin/wozhua.png" },
  { code: "[太阳]", name: "太阳", url: "/emoji/douyin/taiyang.png" },
  { code: "[月亮]", name: "月亮", url: "/emoji/douyin/yueliang.png" },
  { code: "[给跪了]", name: "给跪了", url: "/emoji/douyin/geiguile.png" },
  { code: "[蕉绿]", name: "蕉绿", url: "/emoji/douyin/jiaolv.png" },
  { code: "[扎心]", name: "扎心", url: "/emoji/douyin/zhaxin.png" },
  { code: "[胡瓜]", name: "黄瓜", url: "/emoji/douyin/hugua.png" },
  { code: "[打call]", name: "打call", url: "/emoji/douyin/dacall.png" },
  { code: "[栓Q]", name: "栓Q猫", url: "/emoji/douyin/shuanq.png" },
  { code: "[雪花]", name: "雪花", url: "/emoji/douyin/xuehua.png" },
  { code: "[圣诞树]", name: "圣诞树", url: "/emoji/douyin/shengdanshu.png" },
  { code: "[平安果]", name: "苹果", url: "/emoji/douyin/pinganguo.png" },
  { code: "[圣诞帽]", name: "圣诞帽", url: "/emoji/douyin/shengdanmao.png" },
  { code: "[气球]", name: "气球", url: "/emoji/douyin/qiqiu.png" },
  { code: "[烟花]", name: "烟花", url: "/emoji/douyin/yanhua.png" },
  { code: "[福]", name: "福", url: "/emoji/douyin/fu.png" },
  { code: "[candy]", name: "糖果", url: "/emoji/douyin/candy.png" },
  { code: "[糖葫芦]", name: "糖葫芦", url: "/emoji/douyin/tanghulu.png" },
  { code: "[鞭炮]", name: "鞭炮", url: "/emoji/douyin/bianpao.png" },
  { code: "[元宝]", name: "元宝", url: "/emoji/douyin/yuanbao.png" },
  { code: "[灯笼]", name: "灯笼", url: "/emoji/douyin/denglong.png" },
  { code: "[锦鲤]", name: "锦鲤", url: "/emoji/douyin/jinli.png" },
  { code: "[巧克力]", name: "巧克力", url: "/emoji/douyin/qiaokeli.png" },
  { code: "[戒指]", name: "戒指", url: "/emoji/douyin/jiezhi.png" },
  { code: "[棒棒糖]", name: "棒棒糖", url: "/emoji/douyin/bangbangtang.png" },
  { code: "[纸飞机]", name: "纸飞机", url: "/emoji/douyin/zhifeiji.png" },
  { code: "[粽子]", name: "粽子", url: "/emoji/douyin/zongzi.png" },
];
