export interface EmojiItem {
  emoji: string;
  label: string;
}

export interface EmojiCategory {
  name: string;
  icon: string;
  emojis: EmojiItem[];
}

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    name: "表情",
    icon: "😀",
    emojis: [
      { emoji: "😀", label: "大笑" },
      { emoji: "😃", label: "笑脸" },
      { emoji: "😄", label: "开心" },
      { emoji: "😁", label: "嘿嘿" },
      { emoji: "😆", label: "咧嘴笑" },
      { emoji: "😅", label: "汗笑" },
      { emoji: "🤣", label: "笑哭" },
      { emoji: "😂", label: "喜极而泣" },
      { emoji: "🙂", label: "微笑" },
      { emoji: "😊", label: "害羞" },
      { emoji: "😇", label: "天使" },
      { emoji: "🥰", label: "恋爱" },
      { emoji: "😍", label: "花痴" },
      { emoji: "🤩", label: "星星眼" },
      { emoji: "😘", label: "飞吻" },
      { emoji: "😗", label: "亲亲" },
      { emoji: "😚", label: "闭眼亲" },
      { emoji: "😙", label: "微笑亲" },
      { emoji: "🥲", label: "含泪微笑" },
      { emoji: "😋", label: "好吃" },
      { emoji: "😛", label: "吐舌" },
      { emoji: "😜", label: "调皮" },
      { emoji: "🤪", label: "疯狂" },
      { emoji: "😝", label: "吐眼" },
      { emoji: "🤑", label: "发财" },
      { emoji: "🤗", label: "抱抱" },
      { emoji: "🤭", label: "偷笑" },
      { emoji: "🫢", label: "惊讶" },
      { emoji: "🫣", label: "捂眼" },
      { emoji: "🤫", label: "嘘" },
      { emoji: "🤔", label: "思考" },
      { emoji: "🫡", label: "敬礼" },
      { emoji: "🤐", label: "拉链嘴" },
      { emoji: "🤨", label: "挑眉" },
      { emoji: "😐", label: "无语" },
      { emoji: "😑", label: "不高兴" },
      { emoji: "😶", label: "沉默" },
      { emoji: "😏", label: "得意" },
      { emoji: "😒", label: "白眼" },
      { emoji: "🙄", label: "翻白眼" },
      { emoji: "😬", label: "龇牙" },
      { emoji: "🤥", label: "说谎" },
      { emoji: "😌", label: "-relieved" },
      { emoji: "😔", label: "失望" },
      { emoji: "😪", label: "困" },
      { emoji: "🤤", label: "流口水" },
      { emoji: "😴", label: "睡觉" },
      { emoji: "😷", label: "口罩" },
      { emoji: "🤒", label: "发烧" },
      { emoji: "🤕", label: "受伤" },
      { emoji: "🤢", label: "恶心" },
      { emoji: "🤮", label: "呕吐" },
      { emoji: "🥵", label: "热" },
      { emoji: "🥶", label: "冷" },
      { emoji: "🥴", label: "晕" },
      { emoji: "😵", label: "头晕" },
      { emoji: "🤯", label: "爆炸头" },
      { emoji: "🤠", label: "牛仔" },
      { emoji: "🥳", label: "派对" },
      { emoji: "🥸", label: "伪装" },
      { emoji: "😎", label: "酷" },
      { emoji: "🤓", label: "书呆子" },
      { emoji: "🧐", label: "审视" },
      { emoji: "😕", label: "困惑" },
      { emoji: "🫤", label: "斜嘴" },
      { emoji: "😟", label: "担心" },
      { emoji: "🙁", label: "微皱眉" },
      { emoji: "☹️", label: "皱眉" },
      { emoji: "😮", label: "惊讶" },
      { emoji: "😯", label: "震惊" },
      { emoji: "😲", label: "惊喜" },
      { emoji: "😳", label: "脸红" },
      { emoji: "🥺", label: "恳求" },
      { emoji: "🥹", label: "忍泪" },
      { emoji: "😦", label: "啊" },
      { emoji: "😧", label: "苦恼" },
      { emoji: "😨", label: "害怕" },
      { emoji: "😰", label: "冷汗" },
      { emoji: "😥", label: "难过" },
      { emoji: "😢", label: "流泪" },
      { emoji: "😭", label: "大哭" },
      { emoji: "😱", label: "尖叫" },
      { emoji: "😖", label: "纠结" },
      { emoji: "😣", label: "忍耐" },
      { emoji: "😞", label: "沮丧" },
      { emoji: "😓", label: "汗" },
      { emoji: "😩", label: "累" },
      { emoji: "😫", label: "疲惫" },
      { emoji: "🥱", label: "打哈欠" },
      { emoji: "😤", label: "生气" },
      { emoji: "😡", label: "愤怒" },
      { emoji: "😠", label: "恼怒" },
      { emoji: "🤬", label: "骂人" },
      { emoji: "😈", label: "恶魔笑" },
      { emoji: "👿", label: "恶魔" },
      { emoji: "💀", label: "骷髅" },
      { emoji: "💩", label: "便便" },
      { emoji: "🤡", label: "小丑" },
      { emoji: "👻", label: "鬼" },
      { emoji: "👽", label: "外星人" },
      { emoji: "🤖", label: "机器人" },
    ],
  },
  {
    name: "手势",
    icon: "👋",
    emojis: [
      { emoji: "👋", label: "挥手" },
      { emoji: "🤚", label: "举手" },
      { emoji: "✋", label: "停" },
      { emoji: "🖖", label: "Vulcan" },
      { emoji: "🫱", label: "右手" },
      { emoji: "🫲", label: "左手" },
      { emoji: "🫳", label: "向下手" },
      { emoji: "🫴", label: "向上手" },
      { emoji: "👌", label: "OK" },
      { emoji: "🤌", label: "意大利手势" },
      { emoji: "🤏", label: "捏" },
      { emoji: "✌️", label: "胜利" },
      { emoji: "🤞", label: "交叉手指" },
      { emoji: "🫰", label: "比心" },
      { emoji: "🤟", label: "摇滚" },
      { emoji: "🤘", label: " horns" },
      { emoji: "🤙", label: "打电话" },
      { emoji: "👈", label: "向左指" },
      { emoji: "👉", label: "向右指" },
      { emoji: "👆", label: "向上指" },
      { emoji: "🖕", label: "中指" },
      { emoji: "👇", label: "向下指" },
      { emoji: "👍", label: "赞" },
      { emoji: "👎", label: "踩" },
      { emoji: "✊", label: "拳头" },
      { emoji: "👊", label: "打" },
      { emoji: "🤛", label: "左拳" },
      { emoji: "🤜", label: "右拳" },
      { emoji: "👏", label: "鼓掌" },
      { emoji: "🙌", label: "庆祝" },
      { emoji: "🫶", label: "比心" },
      { emoji: "👐", label: "张开手" },
      { emoji: "🤲", label: "双手摊开" },
      { emoji: "🤝", label: "握手" },
      { emoji: "🙏", label: "祈祷" },
      { emoji: "💪", label: "肌肉" },
    ],
  },
  {
    name: "爱心",
    icon: "❤️",
    emojis: [
      { emoji: "❤️", label: "红心" },
      { emoji: "🧡", label: "橙心" },
      { emoji: "💛", label: "黄心" },
      { emoji: "💚", label: "绿心" },
      { emoji: "💙", label: "蓝心" },
      { emoji: "💜", label: "紫心" },
      { emoji: "🖤", label: "黑心" },
      { emoji: "🤍", label: "白心" },
      { emoji: "🤎", label: "棕心" },
      { emoji: "💔", label: "碎心" },
      { emoji: "❤️‍🔥", label: "燃烧的心" },
      { emoji: "💕", label: "两颗心" },
      { emoji: "💞", label: "旋转心" },
      { emoji: "💓", label: "跳动心" },
      { emoji: "💗", label: "增涨心" },
      { emoji: "💖", label: "闪耀心" },
      { emoji: "💘", label: "丘比特" },
      { emoji: "💝", label: "礼物心" },
      { emoji: "💟", label: "心形装饰" },
      { emoji: "♥️", label: "红心" },
      { emoji: "💋", label: "吻" },
      { emoji: "💯", label: "满分" },
      { emoji: "✨", label: "闪耀" },
      { emoji: "🔥", label: "火焰" },
      { emoji: "⭐", label: "星星" },
      { emoji: "🌟", label: "发光星" },
      { emoji: "💫", label: "流星" },
    ],
  },
  {
    name: "动物",
    icon: "🐶",
    emojis: [
      { emoji: "🐶", label: "狗" },
      { emoji: "🐱", label: "猫" },
      { emoji: "🐭", label: "老鼠" },
      { emoji: "🐹", label: "仓鼠" },
      { emoji: "🐰", label: "兔子" },
      { emoji: "🦊", label: "狐狸" },
      { emoji: "🐻", label: "熊" },
      { emoji: "🐼", label: "熊猫" },
      { emoji: "🐻‍❄️", label: "北极熊" },
      { emoji: "🐨", label: "考拉" },
      { emoji: "🐯", label: "老虎" },
      { emoji: "🦁", label: "狮子" },
      { emoji: "🐮", label: "牛" },
      { emoji: "🐷", label: "猪" },
      { emoji: "🐸", label: "青蛙" },
      { emoji: "🐵", label: "猴子" },
      { emoji: "🙈", label: "非礼勿视" },
      { emoji: "🙉", label: "非礼勿听" },
      { emoji: "🙊", label: "非礼勿言" },
      { emoji: "🐔", label: "鸡" },
      { emoji: "🐧", label: "企鹅" },
      { emoji: "🐦", label: "鸟" },
      { emoji: "🐤", label: "小鸡" },
      { emoji: "🐣", label: "孵化" },
      { emoji: "🐥", label: "小鸭" },
      { emoji: "🦆", label: "鸭" },
      { emoji: "🦅", label: "鹰" },
      { emoji: "🦉", label: "猫头鹰" },
      { emoji: "🦇", label: "蝙蝠" },
      { emoji: "🐺", label: "狼" },
      { emoji: "🐗", label: "野猪" },
      { emoji: "🐴", label: "马" },
      { emoji: "🦄", label: "独角兽" },
      { emoji: "🐝", label: "蜜蜂" },
      { emoji: "🪱", label: "虫" },
      { emoji: "🐛", label: "毛毛虫" },
      { emoji: "🦋", label: "蝴蝶" },
      { emoji: "🐌", label: "蜗牛" },
      { emoji: "🐞", label: "瓢虫" },
      { emoji: "🐜", label: "蚂蚁" },
      { emoji: "🪰", label: "苍蝇" },
      { emoji: "🪲", label: "甲虫" },
      { emoji: "🪳", label: "蟑螂" },
      { emoji: "🦟", label: "蚊子" },
      { emoji: "🦗", label: "蟋蟀" },
      { emoji: "🕷️", label: "蜘蛛" },
      { emoji: "🐢", label: "乌龟" },
      { emoji: "🐍", label: "蛇" },
      { emoji: "🦎", label: "蜥蜴" },
      { emoji: "🐙", label: "章鱼" },
      { emoji: "🦑", label: "鱿鱼" },
      { emoji: "🦐", label: "虾" },
      { emoji: "🦞", label: "龙虾" },
      { emoji: "🦀", label: "螃蟹" },
      { emoji: "🐡", label: "河豚" },
      { emoji: "🐠", label: "热带鱼" },
      { emoji: "🐟", label: "鱼" },
      { emoji: "🐬", label: "海豚" },
      { emoji: "🐳", label: "鲸鱼" },
      { emoji: "🐋", label: "大鲸" },
      { emoji: "🦈", label: "鲨鱼" },
    ],
  },
  {
    name: "食物",
    icon: "🍔",
    emojis: [
      { emoji: "🍏", label: "青苹果" },
      { emoji: "🍎", label: "苹果" },
      { emoji: "🍐", label: "梨" },
      { emoji: "🍊", label: "橘子" },
      { emoji: "🍋", label: "柠檬" },
      { emoji: "🍌", label: "香蕉" },
      { emoji: "🍉", label: "西瓜" },
      { emoji: "🍇", label: "葡萄" },
      { emoji: "🍓", label: "草莓" },
      { emoji: "🫐", label: "蓝莓" },
      { emoji: "🍈", label: "甜瓜" },
      { emoji: "🍒", label: "樱桃" },
      { emoji: "🍑", label: "桃子" },
      { emoji: "🥭", label: "芒果" },
      { emoji: "🍍", label: "菠萝" },
      { emoji: "🥥", label: "椰子" },
      { emoji: "🥝", label: "猕猴桃" },
      { emoji: "🍅", label: "番茄" },
      { emoji: "🍆", label: "茄子" },
      { emoji: "🥑", label: "牛油果" },
      { emoji: "🥦", label: "西兰花" },
      { emoji: "🥬", label: "生菜" },
      { emoji: "🥒", label: "黄瓜" },
      { emoji: "🌶️", label: "辣椒" },
      { emoji: "🫑", label: "甜椒" },
      { emoji: "🌽", label: "玉米" },
      { emoji: "🥕", label: "胡萝卜" },
      { emoji: "🧄", label: "大蒜" },
      { emoji: "🧅", label: "洋葱" },
      { emoji: "🥔", label: "土豆" },
      { emoji: "🍠", label: "红薯" },
      { emoji: "🍞", label: "面包" },
      { emoji: "🥐", label: "牛角包" },
      { emoji: "🥖", label: "法棍" },
      { emoji: "🧀", label: "奶酪" },
      { emoji: "🥚", label: "鸡蛋" },
      { emoji: "🍳", label: "煎蛋" },
      { emoji: "🧈", label: "黄油" },
      { emoji: "🥞", label: "松饼" },
      { emoji: "🧇", label: "华夫饼" },
      { emoji: "🥓", label: "培根" },
      { emoji: "🥩", label: "肉" },
      { emoji: "🍗", label: "鸡腿" },
      { emoji: "🍖", label: "排骨" },
      { emoji: "🌭", label: "热狗" },
      { emoji: "🍔", label: "汉堡" },
      { emoji: "🍟", label: "薯条" },
      { emoji: "🍕", label: "披萨" },
      { emoji: "🫓", label: "饼" },
      { emoji: "🥪", label: "三明治" },
      { emoji: "🌮", label: "墨西哥卷" },
      { emoji: "🌯", label: "卷饼" },
      { emoji: "🫔", label: "粽子" },
      { emoji: "🥙", label: "Pita" },
      { emoji: "🧆", label: "丸子" },
      { emoji: "🥚", label: "蛋" },
      { emoji: "🍜", label: "面条" },
      { emoji: "🍝", label: "意面" },
      { emoji: "🍛", label: "咖喱" },
      { emoji: "🍣", label: "寿司" },
      { emoji: "🍱", label: "便当" },
      { emoji: "🥟", label: "饺子" },
      { emoji: "🦪", label: "生蚝" },
      { emoji: "🍤", label: "虾仁" },
      { emoji: "🍙", label: "饭团" },
      { emoji: "🍚", label: "米饭" },
      { emoji: "🍘", label: "仙贝" },
      { emoji: "🍥", label: "鱼板" },
      { emoji: "🥠", label: "幸运饼干" },
      { emoji: "🥮", label: "月饼" },
      { emoji: "🍢", label: "关东煮" },
      { emoji: "🍡", label: "团子" },
      { emoji: "🍧", label: "刨冰" },
      { emoji: "🍨", label: "冰淇淋" },
      { emoji: "🍦", label: "甜筒" },
      { emoji: "🥧", label: "派" },
      { emoji: "🧁", label: "杯子蛋糕" },
      { emoji: "🍰", label: "蛋糕" },
      { emoji: "🎂", label: "生日蛋糕" },
      { emoji: "🍮", label: "布丁" },
      { emoji: "🍭", label: "棒棒糖" },
      { emoji: "🍬", label: "糖果" },
      { emoji: "🍫", label: "巧克力" },
      { emoji: "🍿", label: "爆米花" },
      { emoji: "🍩", label: "甜甜圈" },
      { emoji: "🍪", label: "饼干" },
      { emoji: "🌰", label: "栗子" },
      { emoji: "🥜", label: "花生" },
      { emoji: "🍯", label: "蜂蜜" },
      { emoji: "🥛", label: "牛奶" },
      { emoji: "☕", label: "咖啡" },
      { emoji: "🫖", label: "茶壶" },
      { emoji: "🍵", label: "茶" },
      { emoji: "🍶", label: "清酒" },
      { emoji: "🍾", label: "香槟" },
      { emoji: "🍷", label: "红酒" },
      { emoji: "🍸", label: "鸡尾酒" },
      { emoji: "🍹", label: "热带饮品" },
      { emoji: "🍺", label: "啤酒" },
      { emoji: "🍻", label: "干杯" },
      { emoji: "🥂", label: "碰杯" },
      { emoji: "🥃", label: "威士忌" },
    ],
  },
  {
    name: "物品",
    icon: "💡",
    emojis: [
      { emoji: "⌚", label: "手表" },
      { emoji: "📱", label: "手机" },
      { emoji: "💻", label: "电脑" },
      { emoji: "⌨️", label: "键盘" },
      { emoji: "🖥️", label: "显示器" },
      { emoji: "🖨️", label: "打印机" },
      { emoji: "🖱️", label: "鼠标" },
      { emoji: "💾", label: "软盘" },
      { emoji: "💿", label: "光盘" },
      { emoji: "📀", label: "DVD" },
      { emoji: "📷", label: "相机" },
      { emoji: "📸", label: "拍照" },
      { emoji: "📹", label: "摄像机" },
      { emoji: "🎥", label: "电影" },
      { emoji: "📽️", label: "放映机" },
      { emoji: "📺", label: "电视" },
      { emoji: "📻", label: "收音机" },
      { emoji: "🎙️", label: "麦克风" },
      { emoji: "🎚️", label: "混音" },
      { emoji: "🎛️", label: "控制台" },
      { emoji: "🧭", label: "指南针" },
      { emoji: "⏱️", label: "秒表" },
      { emoji: "⏰", label: "闹钟" },
      { emoji: "🔋", label: "电池" },
      { emoji: "🔌", label: "插头" },
      { emoji: "💡", label: "灯泡" },
      { emoji: "🔦", label: "手电筒" },
      { emoji: "🕯️", label: "蜡烛" },
      { emoji: "🧯", label: "灭火器" },
      { emoji: "🗑️", label: "垃圾桶" },
      { emoji: "💰", label: "钱袋" },
      { emoji: "💵", label: "美元" },
      { emoji: "💴", label: "日元" },
      { emoji: "💶", label: "欧元" },
      { emoji: "💷", label: "英镑" },
      { emoji: "💳", label: "信用卡" },
      { emoji: "🧾", label: "收据" },
      { emoji: "✉️", label: "信封" },
      { emoji: "📧", label: "邮件" },
      { emoji: "📨", label: "收信" },
      { emoji: "📩", label: "发信" },
      { emoji: "📦", label: "包裹" },
      { emoji: "🏷️", label: "标签" },
      { emoji: "📌", label: "图钉" },
      { emoji: "📎", label: "回形针" },
      { emoji: "🖇️", label: "连环回形针" },
      { emoji: "📏", label: "直尺" },
      { emoji: "📐", label: "三角尺" },
      { emoji: "✂️", label: "剪刀" },
      { emoji: "🖊️", label: "钢笔" },
      { emoji: "🖋️", label: "圆珠笔" },
      { emoji: "✒️", label: "铅笔" },
      { emoji: "🖌️", label: "画笔" },
      { emoji: "🖍️", label: "蜡笔" },
      { emoji: "📝", label: "备忘录" },
      { emoji: "📁", label: "文件夹" },
      { emoji: "📂", label: "打开文件夹" },
      { emoji: "🗂️", label: "卡片" },
      { emoji: "📅", label: "日历" },
      { emoji: "📆", label: "撕日历" },
      { emoji: "📇", label: "索引卡" },
      { emoji: "📈", label: "上升图表" },
      { emoji: "📉", label: "下降图表" },
      { emoji: "📊", label: "柱状图" },
      { emoji: "📋", label: "剪贴板" },
      { emoji: "📌", label: "图钉" },
      { emoji: "📍", label: "定位" },
      { emoji: "🔒", label: "锁" },
      { emoji: "🔓", label: "开锁" },
      { emoji: "🔑", label: "钥匙" },
      { emoji: "🗝️", label: "老钥匙" },
    ],
  },
  {
    name: "符号",
    icon: "💯",
    emojis: [
      { emoji: "💯", label: "满分" },
      { emoji: "✅", label: "对号" },
      { emoji: "❌", label: "叉号" },
      { emoji: "❎", label: "方框叉" },
      { emoji: "❗", label: "感叹号" },
      { emoji: "❕", label: "白感叹" },
      { emoji: "❓", label: "问号" },
      { emoji: "❔", label: "白问号" },
      { emoji: "‼️", label: "双感叹" },
      { emoji: "⁉️", label: "感叹问号" },
      { emoji: "⚠️", label: "警告" },
      { emoji: "🚫", label: "禁止" },
      { emoji: "⛔", label: "禁止通行" },
      { emoji: "🔕", label: "静音" },
      { emoji: "🔕", label: "无铃" },
      { emoji: "🔴", label: "红圆" },
      { emoji: "🟠", label: "橙圆" },
      { emoji: "🟡", label: "黄圆" },
      { emoji: "🟢", label: "绿圆" },
      { emoji: "🔵", label: "蓝圆" },
      { emoji: "🟣", label: "紫圆" },
      { emoji: "⚫", label: "黑圆" },
      { emoji: "⚪", label: "白圆" },
      { emoji: "🟤", label: "棕圆" },
      { emoji: "🔸", label: "小橙菱" },
      { emoji: "🔹", label: "小蓝菱" },
      { emoji: "🔶", label: "大橙菱" },
      { emoji: "🔷", label: "大蓝菱" },
      { emoji: "🔺", label: "红三角" },
      { emoji: "🔻", label: "倒红三角" },
      { emoji: "💠", label: "钻石" },
      { emoji: "🔘", label: "按钮" },
      { emoji: "🔳", label: "白方框" },
      { emoji: "🔲", label: "黑方框" },
      { emoji: "▪️", label: "小黑方" },
      { emoji: "▫️", label: "小白方" },
      { emoji: "◾", label: "中黑方" },
      { emoji: "◽", label: "中白方" },
      { emoji: "◼️", label: "大黑方" },
      { emoji: "◻️", label: "大白方" },
      { emoji: "🟥", label: "红方" },
      { emoji: "🟧", label: "橙方" },
      { emoji: "🟨", label: "黄方" },
      { emoji: "🟩", label: "绿方" },
      { emoji: "🟦", label: "蓝方" },
      { emoji: "🟪", label: "紫方" },
      { emoji: "⬛", label: "大黑方" },
      { emoji: "⬜", label: "大白方" },
      { emoji: "🟫", label: "棕方" },
      { emoji: "♈", label: "白羊" },
      { emoji: "♉", label: "金牛" },
      { emoji: "♊", label: "双子" },
      { emoji: "♋", label: "巨蟹" },
      { emoji: "♌", label: "狮子" },
      { emoji: "♍", label: "处女" },
      { emoji: "♎", label: "天秤" },
      { emoji: "♏", label: "天蝎" },
      { emoji: "♐", label: "射手" },
      { emoji: "♑", label: "摩羯" },
      { emoji: "♒", label: "水瓶" },
      { emoji: "♓", label: "双鱼" },
    ],
  },
];

// B站格式 emoji 映射表
import { DOUYIN_EMOJI_MAP } from "@/lib/douyin-emoji-data";

export const BILIBILI_EMOJI_MAP: Record<string, string> = {
  "[微笑]": "😄",
  "[开心]": "😃",
  "[哈哈]": "😁",
  "[笑cry]": "😂",
  "[笑哭]": "🤣",
  "[泪]": "😢",
  "[流泪]": "😭",
  "[吃惊]": "😲",
  "[惊喜]": "😮",
  "[惊讶]": "🤯",
  "[呆]": "😶",
  "[呆呆]": "😐",
  "[黑线]": "😑",
  "[汗]": "😅",
  "[捂脸]": "🤦",
  "[大哭]": "😭",
  "[喜极而泣]": "🥲",
  "[委屈]": "🥺",
  "[可怜]": "😢",
  "[哭]": "😭",
  "[悲伤]": "😞",
  "[失望]": "😔",
  "[不开心]": "😢",
  "[生气]": "😠",
  "[怒]": "😡",
  "[发怒]": "🤬",
  "[调皮]": "😜",
  "[调皮一笑]": "😜",
  "[滑稽]": "😏",
  "[偷笑]": "🤭",
  "[酷]": "😎",
  "[冷]": "🥶",
  "[思考]": "🤔",
  "[疑问]": "🤨",
  "[疑惑]": "😕",
  "[尴尬]": "😬",
  "[再见]": "👋",
  "[OK]": "👌",
  "[点赞]": "👍",
  "[GOOD]": "👍",
  "[弱]": "👎",
  "[加油]": "💪",
  "[抱拳]": "🙏",
  "[握手]": "🤝",
  "[爱心]": "❤️",
  "[心碎]": "💔",
  "[飞吻]": "😘",
  "[亲亲]": "😗",
  "[抱抱]": "🤗",
  "[礼物]": "🎁",
  "[蛋糕]": "🎂",
  "[鲜花]": "🌸",
  "[太阳]": "☀️",
  "[月亮]": "🌙",
  "[星星]": "⭐",
  "[火]": "🔥",
  "[雷]": "⚡",
  "[凝望星空]": "🤩",
  "[魔性]": "🤪",
  "[囧]": "😦",
  "[吐]": "🤮",
  "[困]": "😴",
  "[瞌睡]": "😴",
  "[萌]": "🥺",
  "[耶]": "✌️",
  "[haha]": "😄",
  "[二哈]": "🐶",
  "[喵喵]": "🐱",
  "[兔子]": "🐰",
  "[老虎]": "🐯",
  "[熊猫]": "🐼",
  "[猪头]": "🐷",
  "[蝴蝶结]": "🎀",
  "[围巾]": "🧣",
  "[奶茶]": "🧋",
  "[干杯]": "🍻",
  "[恭喜]": "🎉",
  "[新年]": "🧧",
  "[红包]": "🧧",
  "[爆竹]": "🧨",
  "[灯笼]": "🏮",
  "[烟花]": "🎆",
  "[雨]": "🌧️",
  "[雪]": "❄️",
  "[气球]": "🎈",
  "[彩虹]": "🌈",
};

// 替换 B站格式 emoji 为 Unicode emoji
export function replaceBilibiliEmoji(text: string): string {
  return text.replace(/\[([^\]]+)\]/g, (match, code) => {
    return BILIBILI_EMOJI_MAP[match] || match;
  });
}

// 渲染 emoji 文本：抖音表情用图片，B站格式转 Unicode
// 返回 HTML 字符串，用于 dangerouslySetInnerHTML
export function renderEmojiText(text: string): string {
  // 先导入抖音表情映射
  const { DOUYIN_EMOJI_MAP } = require("./douyin-emoji-data");

  return text.replace(/\[([^\]]+)\]/g, (match) => {
    // 优先匹配抖音表情（返回 img 标签）
    if (DOUYIN_EMOJI_MAP[match]) {
      const url = DOUYIN_EMOJI_MAP[match];
      return `<img src="${url}" alt="${match}" class="inline-block h-5 w-5 align-middle mx-0.5" draggable="false" />`;
    }
    // 其次匹配 B站格式 emoji（返回 Unicode）
    if (BILIBILI_EMOJI_MAP[match]) {
      return BILIBILI_EMOJI_MAP[match];
    }
    // 都不匹配则原样返回
    return match;
  });
}
